apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalapp2
  namespace: backend2-ns
  labels:
    app: finalapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finalapp2
  template:
    metadata:
      labels:
        app: finalapp2
    spec:
      containers:
        - name: backend2
          image: paulahakeem/finalapp:v3
          ports:
            - containerPort: 80
              protocol: TCP
---
