apiVersion: v1
kind: Service
metadata:
  name: loadbalancer2
  namespace: backend2-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: finalapp2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
