FROM node:14-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --quiet --no-progress

COPY . .

RUN npm run build --quiet --no-progress || exit 1

#deploy stage

FROM nginx

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
